var $jscomp={scope:{},checkStringArgs:function(b,a,c){if(null==b)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(a instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return b+""}};
$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(b,a,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");b!=Array.prototype&&b!=Object.prototype&&(b[a]=c.value)};$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(b,a,c,e){if(a){c=$jscomp.global;b=b.split(".");for(e=0;e<b.length-1;e++){var d=b[e];d in c||(c[d]={});c=c[d]}b=b[b.length-1];e=c[b];a=a(e);a!=e&&null!=a&&$jscomp.defineProperty(c,b,{configurable:!0,writable:!0,value:a})}};
$jscomp.polyfill("String.prototype.endsWith",function(b){return b?b:function(a,b){var c=$jscomp.checkStringArgs(this,a,"endsWith");a+="";void 0===b&&(b=c.length);for(var d=Math.max(0,Math.min(b|0,c.length)),f=a.length;0<f&&0<d;)if(c[--d]!=a[--f])return!1;return 0>=f}},"es6-impl","es3");
$jscomp.polyfill("String.prototype.startsWith",function(b){return b?b:function(a,b){var c=$jscomp.checkStringArgs(this,a,"startsWith");a+="";for(var d=c.length,f=a.length,h=Math.max(0,Math.min(b|0,c.length)),g=0;g<f&&h<d;)if(c[h++]!=a[g++])return!1;return g>=f}},"es6-impl","es3");angular.module("statsApp",["ngRoute","ngAnimate","ui.bootstrap","comments","usermodule"]);
angular.module("statsApp").config(["$routeProvider",function(b){b.when("/welcome",{templateUrl:"tracker/welcome.html"});b.when("/jobs",{templateUrl:"tracker/jobs.html",controller:"joblistCtrl"});b.when("/updates",{templateUrl:"tracker/updates.html",controller:"vcaselistCtrl"});b.when("/rferes",{templateUrl:"tracker/rferes.html",controller:"rferesCtrl"});b.when("/help",{templateUrl:"tracker/help.html"});b.when("/history",{templateUrl:"tracker/history.html",controller:"historyCtrl"});b.when("/profile",
{templateUrl:"work/profile.html",controller:"profCtrl"});b.when("/inbox",{templateUrl:"work/inbox.html",controller:"inboxCtrl"});b.when("/inbox/objform/:tblpk/:rowid",{templateUrl:"work/objform.html",controller:"objformCtrl"});b.when("/inbox/usertbl/:tblpk",{templateUrl:"work/usertbl.html",controller:"usertblCtrl"});b.when("/inbox/objlist/:relpk/:rowid",{templateUrl:"work/objlist.html",controller:"objlistCtrl"});b.when("/inbworks/:workid",{templateUrl:"work/workform.html",controller:"workformCtrl"});
b.when("/404",{templateUrl:"404.html"});b.otherwise({redirectTo:"/welcome"})}]);function getTemp(b){return"/api/temp/rep?a="+b}angular.module("statsApp").run(["$rootScope","$templateCache",function(b,a){b.$on("$routeChangeStart",function(b,e,d){a.removeAll()});b.$on("$viewContentLoaded",function(){a.removeAll()})}]);angular.module("statsApp").constant("tzconfig",{pk_tz_link:2,pk_tz_prof:3,pk_tz_obj:4,pk_tz_postcv:7,pk_tz_postreq:8,pk_tz_proposal:9,pk_tz_work:10,pk_rel_data:2,pk_rel_postcv:12,pk_rel_postreq:15});
angular.module("statsApp").config(["$httpProvider",function(b){b.interceptors.push(["$q","$location",function(a,b){return{request:function(a){console.log("req="+a.url);return a},responseError:function(c){console.log("error:"+c);404===c.status&&b.path("/404");return a.reject(c)},response:function(a){console.log("res-status="+a.status);switch(a.status){case 200:return a;case 404:b.path("/404");break;default:b.path("/error")}}}}])}]);
angular.module("statsApp").service("anchorSmoothScroll",function(){this.scrollTo=function(b){var a=self.pageYOffset?self.pageYOffset:document.documentElement&&document.documentElement.scrollTop?document.documentElement.scrollTop:document.body.scrollTop?document.body.scrollTop:0,c=document.getElementById(b);for(b=c.offsetTop;c.offsetParent&&c.offsetParent!=document.body;)c=c.offsetParent,b+=c.offsetTop;var e=b>a?b-a:a-b;if(100>e)scrollTo(0,b);else{c=Math.round(e/100);20<c&&(c=20);var e=Math.round(e/
25),d=b>a?a+e:a-e,f=0;if(b>a)for(;a<b;a+=e)setTimeout("window.scrollTo(0, "+d+")",f*c),d+=e,d>b&&(d=b),f++;else for(;a>b;a-=e)setTimeout("window.scrollTo(0, "+d+")",f*c),d-=e,d<b&&(d=b),f++}}});angular.module("statsApp").filter("range",function(){return function(b,a){a=parseInt(a);for(var c=0;c<a;c++)b.push(c);return b}});angular.module("statsApp").filter("plus",function(){return function(b){return 0<b?"+"+b:b}});
angular.module("statsApp").filter("dash",function(){return function(b){return null==b||""==b?"-":b}});angular.module("statsApp").filter("rounded",function(){return function(b){return parseInt(b,10)}});angular.module("statsApp").filter("round",function(){return function(b){return Math.round(b)}});angular.module("statsApp").filter("clip",function(){return function(b){return 13>b.length?b:b.substring(0,10)+"..."}});angular.module("statsApp").filter("reverse",function(){return function(b){return b.slice().reverse()}});
angular.module("statsApp").filter("escape",function(){return window.encodeURIComponent});
angular.module("statsApp").filter("timeago",function(){return function(b){if(void 0==b)return"";var a=b.split(" ");b=a[0].split("-");a=a[1].split(":");b=new Date(parseInt(b[0]),parseInt(b[1])-1,parseInt(b[2]),parseInt(a[0]),parseInt(a[1]),parseInt(a[2]));b.setTime(b.getTime()-6E4*b.getTimezoneOffset());b=Math.floor((new Date-b)/1E3);return 31536E3<=b?(b=Math.floor(b/31536E3),b+(1<b?" years":"year")):2592E3<=b?(b=Math.floor(b/2592E3),b+(1<b?" months":" month")):86400<=b?(b=Math.floor(b/86400),b+(1<
b?" days":" day")):3600<=b?(b=Math.floor(b/3600),b+(1<b?" hrs":" hr")):60<=b?(b=Math.floor(b/60),b+" min"):b+" sec"}});
angular.module("statsApp").constant("countries",[{code:"in",name:"India"},{code:"us",name:"United States"},{code:"gb",name:"United Kingdom"},{code:"au",name:"Australia"},{code:"sg",name:"Singapore"},{code:"ca",name:"Canada"},{code:"cn",name:"China"},{code:"ph",name:"Philippines"},{code:"ar",name:"Argentina"},{code:"at",name:"Austria"},{code:"bh",name:"Bahrain"},{code:"be",name:"Belgium"},{code:"br",name:"Brazil"},{code:"cl",name:"Chile"},{code:"co",name:"Colombia"},{code:"cr",name:"Costa Rica"},{code:"cz",
name:"Czech Republic"},{code:"dk",name:"Denmark"},{code:"ec",name:"Ecuador"},{code:"eg",name:"Egypt"},{code:"fi",name:"Finland"},{code:"fr",name:"France"},{code:"de",name:"Germany"},{code:"gr",name:"Greece"},{code:"hk",name:"Hong Kong"},{code:"hu",name:"Hungary"},{code:"id",name:"Indonesia"},{code:"ie",name:"Ireland"},{code:"il",name:"Israel"},{code:"it",name:"Italy"},{code:"jp",name:"Japan"},{code:"kw",name:"Kuwait"},{code:"lu",name:"Luxembourg"},{code:"my",name:"Malaysia"},{code:"mx",name:"Mexico"},
{code:"ma",name:"Morocco"},{code:"nl",name:"Netherlands"},{code:"nz",name:"New Zealand"},{code:"ng",name:"Nigeria"},{code:"no",name:"Norway"},{code:"om",name:"Oman"},{code:"pk",name:"Pakistan"},{code:"pa",name:"Panama"},{code:"pe",name:"Peru"},{code:"pl",name:"Poland"},{code:"pt",name:"Portugal"},{code:"qa",name:"Qatar"},{code:"ro",name:"Romania"},{code:"ru",name:"Russia"},{code:"sa",name:"Saudi Arabia"},{code:"za",name:"South Africa"},{code:"kr",name:"South Korea"},{code:"es",name:"Spain"},{code:"se",
name:"Sweden"},{code:"ch",name:"Switzerland"},{code:"tw",name:"Taiwan"},{code:"th",name:"Thailand"},{code:"tr",name:"Turkey"},{code:"ae",name:"UAE"},{code:"ua",name:"Ukraine"},{code:"uy",name:"Uruguay"},{code:"ve",name:"Venezuela"},{code:"vn",name:"Vietnam"}]);angular.module("usermodule",["ui.bootstrap"]);
angular.module("usermodule").factory("usersvc",["$http","$rootScope","$uibModal",function(b,a,c){return{login:function(a){c.open({animation:!0,templateUrl:"login.html",controller:"logindlgCtrl",size:"sm"}).result.then(function(b){console.log("loginst="+b);a(b)},function(){console.log("Modal dismissed");a("cancel")})},signup:function(a){c.open({animation:!0,templateUrl:"signup.html",controller:"addAccountCtrl",size:"sm"}).result.then(function(b){console.log("signupst="+b);a(b)},function(){a("cancel")})},
logout:function(a){b.post("/api/user?a=logout").success(function(b,c,h,g){a("success")})},setprof:function(a,c){b.post("/api/user?a=setprof&profid="+a).success(function(a,b,g,d){console.log("profile="+a);localStorage.setItem("wtprofile",JSON.stringify(a));c("success")})},checklogin:function(a){b.get("/api/user?a=checklogin").success(function(b,c,h,g){a(b)})}}}]);
angular.module("usermodule").controller("addAccountCtrl",["$scope","$http","$uibModalInstance",function(b,a,c){b.error="";b.ok=function(){var e=b.user;null==e.userid||4>e.userid.trim().length?b.error="User id needs atleast 4 letters":null==e.pass||6>e.pass.trim().length?b.error="Password needs atleast 6 letters":e.pass!=e.pass2?b.error="Passwords do not match":a.get("/api/user?a=checkuserid&id="+e.userid).success(function(d,f,h,g){console.log(d.status);"success"==d.status?a.post("/api/user?a=signup",
e).success(function(a,b,g,f){c.close("success")}):"id_exists"==d.status&&(b.error="That user id is already taken. Please try a different one.")})};b.cancel=function(){c.dismiss("cancel")}}]);
angular.module("usermodule").controller("logindlgCtrl",["$scope","$http","$window","$uibModalInstance",function(b,a,c,e){b.error="";b.ok=function(){var d=b.user;null==d.userid||4>d.userid.trim().length?b.error="User id needs atleast 4 letters":null==d.pass||6>d.pass.trim().length?b.error="Password needs atleast 6 letters":(d=c.btoa(d.userid+":"+d.pass),console.log("authdata="+d),a.defaults.headers.common.Authorization="Basic "+d,a.post("/api/user?a=login").success(function(a,c,g,d){null==a?b.error=
"Error while logging in. Please try again later.":e.close("success")}).error(function(a,c){401==c&&(b.error="Invalid input. Please try again.")}))};b.cancel=function(){e.dismiss("cancel")}}]);angular.module("usermodule").controller("appsCtrl",["$scope","$uibModalInstance",function(b,a){b.error="";b.ok=function(b){console.log("ok="+b);a.close(b)};b.cancel=function(){a.dismiss("cancel")}}]);
angular.module("comments",[]).directive("cmtvcase",function(){return{restrict:"E",scope:{},templateUrl:"tracker/cmtvcase.html",controller:["countries","$scope","$http","$attrs","$interval",function(b,a,c,e,d){a.countries=b;a.sz=100;a.topic=e.topic;a.fltrmode=!1;a.uinfoedit=!1;a.cmtloaded=!1;a.editmode=!1;a.fltrdata=!1;a.page=1;a.cmt={name:localStorage.getItem("wt_name")};a.blank=function(a){return null==a||void 0==a?"":a};a.uinfo={};switch(a.topic){case "2":a.uinfo.name=a.blank(localStorage.getItem("wt_name")),
a.uinfo.status=a.blank(localStorage.getItem("wt_status")),a.uinfo.center=a.blank(localStorage.getItem("wt_center")),a.uinfo.series=a.blank(localStorage.getItem("wt_series")),a.uinfo.rfereason=a.blank(localStorage.getItem("wt_rfereason")),a.uinfo.degree=a.blank(localStorage.getItem("wt_degree")),a.uinfo.processing=a.blank(localStorage.getItem("wt_processing")),a.uinfo.skill=a.blank(localStorage.getItem("wt_skill")),a.uinfo.company=a.blank(localStorage.getItem("wt_company")),a.uinfo.empcity=a.blank(localStorage.getItem("wt_empcity")),
a.uinfo.country=a.blank(localStorage.getItem("wt_country")),a.statusopts=";RFE;RFE Resp Sent;Received;Approved;Name Updated;Other".split(";")}a.loadcomments=function(b){a.cmtloaded=!1;var f=localStorage.getItem("wt_id");null==f&&(f="");a.fltrmode?c.post("/api/data/comments?action=filter&topic="+a.topic+"&u="+f+"&p="+b+"&sz="+a.sz,a.fltr).success(function(c,f,d,h){a.cset=c;a.page=b;a.fltrdata=!0;a.cmtloaded=!0}):c.get("/api/data/comments?topic="+a.topic+"&u="+f+"&p="+b+"&sz="+a.sz).success(function(c,
f,d,h){a.cset=c;a.page=b;a.cmtloaded=!0})};a.filtercomments=function(b){a.loadcomments(1)};a.upvote=function(a){if(!a.owner){var b=JSON.parse(localStorage.getItem("wt_votes"));null==b&&(b=[]);-1==b.indexOf(a.pk)&&(a.votes++,b.push(a.pk),localStorage.setItem("wt_votes",JSON.stringify(b)),c.post("/api/data/comments?action=upvote",a.pk).success(function(a,b,c,f){}))}};a.showfltr=function(b){a.fltrmode=b};a.clearfltr=function(){document.getElementById("form2").reset();a.fltrdata=!1;a.fltrmode=!1;a.loadcomments(1)};
a.canceluinfo=function(){a.uinfo.name=localStorage.getItem("wt_name");a.uinfo.status=localStorage.getItem("wt_status");a.uinfo.center=localStorage.getItem("wt_center");a.uinfo.series=localStorage.getItem("wt_series");a.uinfo.rfereason=localStorage.getItem("wt_rfereason");a.uinfo.degree=localStorage.getItem("wt_degree");a.uinfo.processing=localStorage.getItem("wt_processing");a.uinfo.skill=localStorage.getItem("wt_skill");a.uinfo.company=localStorage.getItem("wt_company");a.uinfo.empcity=localStorage.getItem("wt_empcity");
a.uinfo.country=localStorage.getItem("wt_country");a.uinfoedit=!1};a.saveuinfo=function(){localStorage.setItem("wt_name",a.uinfo.name);localStorage.setItem("wt_status",a.uinfo.status);localStorage.setItem("wt_center",a.uinfo.center);localStorage.setItem("wt_series",a.uinfo.series);localStorage.setItem("wt_rfereason",a.uinfo.rfereason);localStorage.setItem("wt_degree",a.uinfo.degree);localStorage.setItem("wt_processing",a.uinfo.processing);localStorage.setItem("wt_skill",a.uinfo.skill);localStorage.setItem("wt_company",
a.uinfo.company);localStorage.setItem("wt_empcity",a.uinfo.empcity);localStorage.setItem("wt_country",a.uinfo.country);a.uinfoedit=!1;var b=localStorage.getItem("wt_id");null==b&&(b=a.guid(),localStorage.setItem("wt_id",b));a.uinfo.id=b;c.post("/api/data/comments?action=uinfo",a.uinfo).success(function(a,b,c,f){})};a.addcomment=function(){if(null==a.uinfo.name||""==a.uinfo.name||void 0==a.uinfo.name)alert("Please provide your name and other info by clicking on 'edit' below and please save it before proceeding with comment");
else{var b=localStorage.getItem("wt_id");null==b&&(b=a.guid(),localStorage.setItem("wt_id",b));a.empty(a.cmt.txt)||(b={user:b,name:a.uinfo.name,topic:a.topic,txt:a.cmt.txt},a.cmt.txt=null,c.post("/api/data/comments",b).success(function(b,c,d,f){a.loadcomments(1);c=JSON.parse(localStorage.getItem("wt_cmts"));null==c&&(c=[]);c.push(parseInt(b.status));localStorage.setItem("wt_cmts",JSON.stringify(c))}))}};a.editcmt=function(b){if(!a.empty(b.txt)){var d=localStorage.getItem("wt_id");null!=d&&c.post("/api/data/comments?action=edit",
{pk:b.pk,user:d,txt:b.txt}).success(function(b,c,d,f){a.loadcomments(a.page)});a.editmode=!1}};a.rmcmt=function(b){if(confirm("Are you sure to delete this comment?")){var d=localStorage.getItem("wt_id");null!=d&&c.post("/api/data/comments?action=del",{pk:b.pk,user:d}).success(function(b,c,d,f){a.loadcomments(a.page)})}};a.guid=function(){return Math.random().toString(36).substring(2,8)+Math.random().toString(36).substring(2,8)};a.empty=function(a){return null==a?!0:""==a.trim()?!0:!1};a.links2html=
function(a){return a.replace(/(\b(https?|ftp|file):\/\/[-A-Z0-9+&@#\/%?=~_|!:,.;]*[-A-Z0-9+&@#\/%=~_|])/ig,"<a href='$1' target=\"_blank\">$1</a>")};a.loadcomments(1);d(function(){a.loadcomments(1)},12E4)}]}});window.chartColors={rec:"#cc0",rfe:"#eae",rrr:"#c90",dnm:"#09f",oth:"#8ce"};Chart.defaults.global.defaultFontColor="#fff";
window.getopts=function(b){return{type:"bar",data:b,options:{title:{display:!1},tooltips:{mode:"index",intersect:!1},responsive:!0,maintainAspectRatio:!1,scales:{xAxes:[{barThickness:4,ticks:{autoSkip:!0,maxTicksLimit:22},gridLines:{display:!1},stacked:!0}],yAxes:[{gridLines:{display:!0,color:"#bbb"},ticks:{max:400,beginAtZero:!0},stacked:!0}]}}}};
angular.module("statsApp").controller("vcaselistCtrl",["$http","$scope","$rootScope","anchorSmoothScroll","$location","$uibModal","$log",function(b,a,c,e,d,f,h){a.loadvcases=function(){b.get("/api/data/vcases/stackedcols?pre=EAC").success(function(a,b,c,d){b=[];c=[];d=[];for(var g=[],f=[],e=[],h=0;h<a.length;h++)b.push(a[h].id.substring(5,8)+"-"+a[h].id.substring(8,10)),c.push(a[h].rec),d.push(a[h].rfe),g.push(a[h].rrr),f.push(a[h].dnm),e.push(a[h].oth);a={labels:b,backgroundColor:"rgba(185, 214, 200, 0.75)",
borderColor:"rgba(255, 255, 255, 0.5)",datasets:[{backgroundColor:window.chartColors.rec,label:"REC",data:c},{backgroundColor:window.chartColors.rfe,label:"RFE",data:d},{backgroundColor:window.chartColors.rrr,label:"RESP",data:g},{backgroundColor:window.chartColors.dnm,label:"DNM",data:f},{backgroundColor:window.chartColors.oth,label:"OTH",data:e}]};b=document.getElementById("canvas_eac").getContext("2d");window.myBar=new Chart(b,window.getopts(a))});b.get("/api/data/vcases/stackedcols?pre=WAC").success(function(a,
b,c,d){b=[];c=[];d=[];for(var f=[],g=[],h=[],e=0;e<a.length;e++)b.push(a[e].id.substring(5,8)+"-"+a[e].id.substring(8,10)),c.push(a[e].rec),d.push(a[e].rfe),f.push(a[e].rrr),g.push(a[e].dnm),h.push(a[e].oth);a={labels:b,backgroundColor:"rgba(185, 214, 200, 0.75)",borderColor:"rgba(255, 255, 255, 0.5)",datasets:[{backgroundColor:window.chartColors.rec,label:"REC",data:c},{backgroundColor:window.chartColors.rfe,label:"RFE",data:d},{backgroundColor:window.chartColors.rrr,label:"RESP",data:f},{backgroundColor:window.chartColors.dnm,
label:"DNM",data:g},{backgroundColor:window.chartColors.oth,label:"OTH",data:h}]};b=document.getElementById("canvas_wac").getContext("2d");window.myBar=new Chart(b,window.getopts(a))})};a.loadvcases();a.eac=[2,2,1,2,2,3,2,2,1,4,5,5,5,5,2,6,6,6,6,6,2,6,7,6,6];a.wac=[1,1,1,1,2,3,3,1,3,5,5,5,4,2,5,4,5,5,5,2,5,5,5,3,3];a.sbs=[[150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,
195,196,197,198,199],[150,151,155,158,161,166,167,169,171,172,173,177,182,184,186,198],[150,151,161,166,167,169,172,186,198],[150,151,172]];a.msloaded=!1;a.sortcol="dt";a.sortdir="desc";a.loadmseries=function(c,d){a.msloaded=!1;a.changes={};a.mseries=[];a.mstot={rec:0,rfe:0,rrr:0,app:0,dnm:0,chg:0};b.get("/api/data/vcases/test?a=mseries&sortcol="+c+"&sortdir="+d).success(function(b,c,d,f){a.mstats=b;b=null;c=!0;d=[0,0,0,0,0,0];for(f=0;f<a.mstats.length;f++){var g=a.mstats[f];null==b&&(b=g.chgdt.substring(0,
10));b==g.chgdt.substring(0,10)?a.mstats[f].cdt=!1:(c=!1,a.mstats[f].cdt=!0,b=g.chgdt.substring(0,10));a.changes[g.id]=g.chgs;a.mseries.push(g.id);a.mstot.rec+=g.rec;a.mstot.rfe+=g.rfe;a.mstot.rrr+=g.rrr;a.mstot.app+=g.app;a.mstot.dnm+=g.dnm;a.mstot.chg+=""==g.chgs?0:g.chgs.split(",").length;g.tchgs={crfe:0,cresp:0,cdnm:0,app1:0,app2:0};if(null!=g.chgst){for(var e=g.chgst.split(","),h=0;h<e.length;h++)e[h].endsWith("7")?g.tchgs.cresp++:e[h].endsWith("8")?g.tchgs.cdnm++:e[h].endsWith("3")?g.tchgs.crfe++:
"01"==e[h]?g.tchgs.app1++:"71"==e[h]&&g.tchgs.app2++;c&&(d[0]+=g.chgs.split(",").length,d[1]+=g.tchgs.crfe,d[2]+=g.tchgs.cresp,d[3]+=g.tchgs.cdnm,d[4]+=g.tchgs.app1,d[5]+=g.tchgs.app2)}}a.msloaded=!0;a.vcaseid||(a.vcaseid=a.mseries[Math.floor(Math.random()*a.mseries.length)],a.getvcase(a.vcaseid,"latest",null,!1));a.cfdtstat=d})};a.loadmseries(a.sortcol,a.sortdir);b.get("/api/data/vcases/test?a=getadmins").success(function(b,c,d,f){a.admins=b});a.setsort=function(b){a.sortdir=a.sortcol==b?""==a.sortdir?
"desc":"":"dt"==b?"desc":"";a.sortcol=b;a.loadmseries(a.sortcol,a.sortdir)};a.sortclr=function(b){return a.sortcol==b?""==a.sortdir?"#cdf":"#fdc":""};a.vcaseform=function(a){d.path("/vcases/"+a)};a.getAgeDays=function(a){a=a.split(" ");var b=a[0].split("-");a[1].split(":");a=new Date(parseInt(b[0]),parseInt(b[1])-1,parseInt(b[2]),0,0,0);a.setTime(a.getTime()-6E4*a.getTimezoneOffset());return Math.floor(Math.floor((new Date-a)/1E3)/86400)};a.getMsbg=function(b){b=a.mseries.indexOf(b);if(-1==b)return"#fff";
b=a.mstats[b];if(b.chguser.startsWith("*"))return"#ccffff";switch(a.getAgeDays(b.chgdt)){case 0:return"#bbf8bb";case 1:return"#f6faaa";case 2:return"#ffddaa";case 3:return"#ffc8e0"}return"#dce4ff"};a.getvcase=function(c,d,f,h){console.log("getvcase called");null!=c&&(console.log("getvcase api called"),a.vcaseid=c,b.get("/api/data/vcases/vcaseform?vcase="+a.vcaseid+(void 0==d?"":"&nav="+d+"&dt="+f)).success(function(b,c,d,f){if("empty"!=b){h&&e.scrollTo("seriesgrid");a.vcase=b;a.res=a.vcase.data.split(",");
a.paths=a.vcase.paths.split("");a.pathdir=0;a.pathrfe=0;a.pathoth=0;for(b=a.pathunk=0;b<a.paths.length;b++)switch(a.paths[b]){case "1":a.pathunk++;break;case "2":a.pathdir++;break;case "6":a.pathoth++;break;case "9":a.pathrfe++}c=[0,0,0,0,0,0,0,0,0];for(b=0;b<a.res.length;b++)switch(a.res[b]){case "0":c[0]++;break;case "1":case "2":case "6":case "9":c[1]++;break;case "3":c[3]++;break;case "4":c[4]++;break;case "5":c[5]++;break;case "7":c[7]++;break;case "8":c[8]++}a.sdetail=c}}))};a.clr="#ee0 #0c0 #fa6 #fbf #acf #fff #bb0 #eb0 #8c8c8c".split(" ");
a.getColor=function(b){return a.clr[b]};a.getClz=function(a){return"c"+a};a.getBorder=function(b,c){return-1!=(","+a.changes[b]+",").indexOf(","+c+",")?"2px solid #008":""};a.history=function(a){f.open({animation:!0,templateUrl:"casehistory.html",controller:"caseHistoryCtrl",size:"sm",resolve:{casenum:function(){return a}}}).result.then(function(a){},function(){})}}]);
angular.module("statsApp").controller("caseHistoryCtrl",["$scope","$http","$uibModalInstance","casenum",function(b,a,c,e){b.casenum=e;b.chgloaded=!1;a.get("/api/data/vcases/?a=history&casenum="+e).success(function(a,c,e,g){b.casehist=a;b.chgloaded=!0});b.ok=function(){c.close("ok")};b.cancel=function(){c.dismiss("cancel")};b.statnames="Received;Approved;Rejected;RFE Req;Other;Not Form I-129;Transferred;RFE resp rec;Decision Notice".split(";");b.getStatus=function(a){return b.statnames[a]}}]);
angular.module("statsApp").controller("helpCtrl",["$http","$scope","$location",function(b,a,c){b.get("/api/data/vcases/test?a=getadmins").success(function(b,c,f,h){a.admins=b})}]);angular.module("statsApp").controller("historyCtrl",["$http","$scope",function(b,a){b.get("/charts?t=0").success(function(b,e,d,f){a.charts=b.slice().reverse()})}]);
angular.module("statsApp").controller("changesCtrl",["$http","$scope",function(b,a){b.get("/api/reports?rep=changes").success(function(b,e,d,f){a.rep=b;a.reptot={chgs:0};for(b=0;b<a.rep.length;b++)a.reptot.chgs+=a.rep[b].chgs})}]);angular.module("statsApp").controller("rferesCtrl",["$http","$scope",function(b,a){b.get("/api/reports?rep=rferes").success(function(b,e,d,f){a.rep=b;a.reptot={app:0,dnm:0};for(b=0;b<a.rep.length;b++)a.reptot.app+=a.rep[b].app,a.reptot.dnm+=a.rep[b].dnm})}]);
angular.module("statsApp").controller("indexCtrl",["$http","$scope","$location","usersvc","$window",function(b,a,c,e,d){b.get("/api/data/vcases/updatedt").success(function(b,c,d,e){a.update=b});a.loggedin=!1;a.signupalert=!1;a.user={name:localStorage.getItem("wt_name"),id:localStorage.getItem("wt_id")};a.signup=function(){e.signup(function(b){"cancel"!=b&&(a.signupalert=!0)})};a.logout=function(){e.logout(function(){a.loggedin=!1;a.prof=null;c.path("/welcome")})};a.login=function(){e.login(function(b){"success"==
b&&(a.loggedin=!0,c.path("/profile"))})}}]);
angular.module("statsApp").controller("joblistCtrl",["countries","$http","$scope","$location",function(b,a,c,e){c.countries=b;c.jf=JSON.parse(localStorage.getItem("wt_job_jf"));null==c.jf&&(c.jf={q:"Java",co:"us",city:"San Francisco"});c.jpage=0;c.jobsel=-1;c.loadjobs=function(b,f){f&&localStorage.setItem("wt_job_jf",JSON.stringify(c.jf));a.get("/jobtrack?a=list&q="+c.jf.q+"&co="+c.jf.co+"&start="+10*b+"&city="+c.jf.city).success(function(a,d,f,e){c.data=a;c.jpage=b})};c.loadjobs(0,!1);c.loadsaved=
function(){var b=JSON.parse(localStorage.getItem("wt_job_cart"));if(null!=b){for(var f="",e=0;e<b.length;e++)f+=b[e]+",";0<b.length&&(f=f.substring(0,f.length-1),a.get("/jobtrack?a=keys&q="+f).success(function(a,b,d,f){c.savedjobs=a}))}};c.loadsaved();c.loadapplied=function(){var b=JSON.parse(localStorage.getItem("wt_job_subs"));if(null!=b){for(var f="",e=0;e<b.length;e++)f+=b[e]+",";0<b.length&&(f=f.substring(0,f.length-1),a.get("/jobtrack?a=keys&q="+f).success(function(a,b,d,e){c.appliedjobs=a}))}};
c.loadapplied();c.showjob=function(a,b){var c=document.getElementById(b+a);c.style.display="none"==c.style.display?"":"none"};c.savejob=function(a,b){var d=JSON.parse(localStorage.getItem("wt_job_cart"));null==d&&(d=[]);0>d.indexOf(a.jobkey)&&(d.push(a.jobkey),localStorage.setItem("wt_job_cart",JSON.stringify(d)),c.loadsaved())};c.applied=function(a,b,e){b=JSON.parse(localStorage.getItem("wt_job_subs"));null==b&&(b=[]);0>b.indexOf(a.jobkey)&&(b.push(a.jobkey),localStorage.setItem("wt_job_subs",JSON.stringify(b)),
c.loadapplied(),"saved"==e&&c.loadsaved())};c.rmsavejob=function(a,b){var d=JSON.parse(localStorage.getItem("wt_job_cart"));null!=d&&(d.indexOf(a),d=d.filter(function(b){return b!==a}),localStorage.setItem("wt_job_cart",JSON.stringify(d)),c.loadsaved())};c.rmapplied=function(a,b){var d=JSON.parse(localStorage.getItem("wt_job_subs"));null!=d&&(d=d.filter(function(b){return b!==a}),localStorage.setItem("wt_job_subs",JSON.stringify(d)),c.loadapplied())}}]);
